In [3]:
import numpy as np
arr=np.array([[1,2,4,5],[5,7,8,9]])
print(arr+4.5)
print(arr)

[[ 5.5  6.5  8.5  9.5]
 [ 9.5 11.5 12.5 13.5]]
[[1 2 4 5]
 [5 7 8 9]]


In [24]:
import numpy as np
arr=np.array([[1,2,4,5],[5,7,8,9]])
arr+=2
print(arr)

[[ 3  4  6  7]
 [ 7  9 10 11]]


In [26]:
import numpy as np
arr=np.array([[1,2,4,5],[5,7,8,9]])
arr*=2
print(arr)

[[ 2  4  8 10]
 [10 14 16 18]]


In [27]:
import numpy as np
A=np.array([[1,2,3],[7,8,9]])
B=np.array([[4,5,6],[8,5,2]])
print(A+B)
print(A*B)

[[ 5  7  9]
 [15 13 11]]
[[ 4 10 18]
 [56 40 18]]
